### ISSUE TITLE
IE Performance is abysmal

### ISSUE THREAD

**Issue by Ungolianth** [stefanrinderle/softvis3d#19]
Has something changed on the WebGL-Side? The Performance of IE is really bad. Even worse, once the debugging console is opened.

Also a new Error appeared, when drawing a city. (It did not occur a week ago!)
```
TypeError: Object doesn't support this action
   at Anonymous function (http://sonar-vbox:80/static/softvis3d/threeViewer/bundle.js:9023:6)
   at Scope.prototype.$broadcast (http://sonar-vbox:80/static/softvis3d/threeViewer/vendor.js:27643:16)
   at ThreeViewer.MessageBus.prototype.broadcast (http://sonar-vbox:80/static/softvis3d/threeViewer/bundle.js:8945:4)
   at ThreeViewer.MessageBus.prototype.trigger (http://sonar-vbox:80/static/softvis3d/threeViewer/bundle.js:8927:4)
   at Anonymous function (http://sonar-vbox:80/static/softvis3d/threeViewer/bundle.js:1736:6)
   at processQueue (http://sonar-vbox:80/static/softvis3d/threeViewer/vendor.js:26046:12)
   at Anonymous function (http://sonar-vbox:80/static/softvis3d/threeViewer/vendor.js:26062:28)
   at Scope.prototype.$eval (http://sonar-vbox:80/static/softvis3d/threeViewer/vendor.js:27320:10)
   at Scope.prototype.$digest (http://sonar-vbox:80/static/softvis3d/threeViewer/vendor.js:27133:16)
   at Scope.prototype
```

**Using IE 11.0.9600**

----------
>Edit:
> Maybe the new draw-size?

**Comment by stefanrinderle** [comment]
Hey, 

the only thing i really did in webgl is to extend the far pane of the visualization camera. I could not see any issues for Firefox, Safari or Chrome with this. 

As i have no windows system available for the next 10 days, could you try out to set the PERP_FAR_PLANE in the camera.js back to 10000?

I did this change because of the bigger size of the city, parts of it sometimes disappeared. I just set it to a really big value (1000000) because i didn't thought that this has any impact on the performance.

@Ungolianth Assigned to you to test other values. Thanks.

**Comment by Ungolianth** [comment]
6f26d810a466353524f5363767649b56c142ef1b fixes the uncaught exception and i visual bug in IE.

For the performance.... Small projects run smooth. Medium Projects (ArgoUML) are still working on an acceptable performance as long as the _debugging tools_ are still closed. Taking a look a those just cracks IE up.

I Guess we can't do much about it. I will test the changes in Safari too, afterwards we can *close* the issue...

**Comment by Ungolianth** [comment]
No additional Errors in Safaris Console --> Close
